-- 코드를 입력하세요
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI2.MAX_FAVORITES
FROM REST_INFO AS RI
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    ) AS RI2
ON RI.FOOD_TYPE = RI2.FOOD_TYPE
AND RI.FAVORITES = RI2.MAX_FAVORITES
ORDER BY FOOD_TYPE DESC;