-- 코드를 입력하세요
SELECT YEAR, MONTH, GENDER, COUNT(DISTINCT(USER_ID)) AS USERS
FROM
(SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, UI.GENDER, UI.USER_ID 
FROM USER_INFO AS UI
JOIN ONLINE_SALE AS OS
ON UI.USER_ID = OS.USER_ID
WHERE UI.GENDER IS NOT NULL) AS TT
GROUP BY MONTH, GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;