-- 코드를 입력하세요
SELECT FLAVOR
FROM
(SELECT FH.FLAVOR, (FH.TOTAL_ORDER + J.TOTAL_ORDER) AS SUM_ORDER 
FROM FIRST_HALF AS FH
JOIN 
(SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR) AS J
ON FH.FLAVOR = J.FLAVOR
ORDER BY SUM_ORDER DESC
LIMIT 3) AS ANSWER;