-- 코드를 입력하세요
SELECT MP.MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
FROM MEMBER_PROFILE AS MP
JOIN REST_REVIEW AS RR
ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_ID IN (
SELECT RR.MEMBER_ID
FROM MEMBER_PROFILE AS MP
JOIN REST_REVIEW AS RR
ON MP.MEMBER_ID = RR.MEMBER_ID
GROUP BY RR.MEMBER_ID
HAVING COUNT(*) = 
    (SELECT COUNT(*) AS C
    FROM MEMBER_PROFILE AS MP
    JOIN REST_REVIEW AS RR
    ON MP.MEMBER_ID = RR.MEMBER_ID
    GROUP BY RR.MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1)
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;