-- 코드를 입력하세요
SELECT DISTINCT(CRCC.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS CRCC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE MONTH(START_DATE) = '10' AND CRCC.CAR_TYPE = '세단'
ORDER BY CRCC.CAR_ID DESC;