-- 코드를 작성해주세요
# SELECT ID, FNI.FISH_NAME, MAX(LENGTH) AS LENGTH
# FROM FISH_INFO AS FI
# JOIN FISH_NAME_INFO AS FNI
# ON FI.FISH_TYPE = FNI.FISH_TYPE
# GROUP BY FI.FISH_TYPE
# ORDER BY ID ASC;

SELECT ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO AS FI
JOIN FISH_NAME_INFO AS FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
RIGHT JOIN 
(
SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
FROM FISH_INFO
GROUP BY FISH_TYPE
) AS FII
ON FII.FISH_TYPE = FI.FISH_TYPE AND FII.LENGTH = FI.LENGTH
ORDER BY ID ASC;