-- 코드를 입력하세요

SELECT FP1.CATEGORY, FP1.PRICE AS MAX_PRICE, FP1.PRODUCT_NAME
FROM FOOD_PRODUCT AS FP1
JOIN (
    SELECT MAX(PRICE) AS MAX_PRICE, CATEGORY
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
    GROUP BY CATEGORY
    ) AS FP2
ON FP1.CATEGORY = FP2.CATEGORY
AND FP1.PRICE = FP2.MAX_PRICE
ORDER BY MAX_PRICE DESC;